export default function MISCompany(){

  const softBtn={
    background:"#f3f4f6",
    border:"1px solid #e5e7eb",
    color:"#374151"
  }

  return(
    <div>

      {/* ===== FILTER SECTION ===== */}
      <div className="row g-3 mb-3">

        <div className="col-md-4">
          <label className="small">Select Company</label>
          <select className="form-select form-select-sm">
            <option>Select</option>
          </select>
        </div>

        <div className="col-md-4">
          <label className="small">Date As On</label>
          <input className="form-control form-control-sm" placeholder="d/m/y"/>
        </div>

        <div className="col-md-3">
          <label className="small">Select Data</label>
          <select className="form-select form-select-sm">
            <option>Select</option>
          </select>
        </div>

        <div className="col-md-1 d-flex align-items-end">
          <button className="btn btn-sm" style={{background:"#2E388E",color:"#fff"}}>
            Generate
          </button>
        </div>

      </div>

      {/* ===== HISTORY TITLE ===== */}
      <h6 className="mb-2">MIS Report History Company</h6>

      {/* ===== CONTROLS ===== */}
      <div className="d-flex justify-content-between mb-2 flex-wrap gap-2">

        <button className="btn btn-sm" style={softBtn}>
          Show 10 entries
        </button>

        <div style={{position:"relative"}}>
          <i className="bi bi-search"
            style={{
              position:"absolute",
              left:"10px",
              top:"50%",
              transform:"translateY(-50%)",
              fontSize:"13px",
              color:"#888"
            }}
          />
          <input
            className="form-control form-control-sm"
            placeholder="Search"
            style={{width:"180px",paddingLeft:"28px"}}
          />
        </div>

      </div>

      {/* ===== TABLE ===== */}
      <div style={{overflowX:"auto"}}>
        <table className="table table-bordered">
          <thead>
            <tr>
              <th>#</th>
              <th>Generated On</th>
              <th>Generated By</th>
              <th>Generated For</th>
              <th>MIS Date as on</th>
              <th>Origin</th>
              <th>Export</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td colSpan={8} className="text-center">
                No data available in table
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      {/* ===== FOOTER ===== */}
      <div
        className="d-flex justify-content-between align-items-center mt-2 pt-2"
        style={{borderTop:"1px solid #e5e7eb"}}
      >
        <small className="text-muted">Showing 0 to 0 of 0 entries</small>

        <div className="d-flex gap-2">
          <button className="btn btn-sm" style={softBtn}>Previous</button>
          <button className="btn btn-sm" style={softBtn}>Next</button>
        </div>
      </div>

    </div>
  )
}