import React from "react";

interface ViewPublicDocumentViewProps {
    onBack: () => void;
}

const ViewPublicDocumentView: React.FC<ViewPublicDocumentViewProps> = ({ onBack }) => {
    return (
        <div className="card shadow-sm border-0 p-4" style={{ borderRadius: "16px", backgroundColor: "#fff" }}>
            {/* ⭐ HEADER */}
            <div className="d-flex justify-content-between align-items-center mb-4 border-bottom pb-3">
                <h5 className="fw-bold mb-0 text-dark">VIEW PUBLIC DOCUMENT - MCA V3</h5>
                <button className="btn btn-primary btn-sm d-flex align-items-center gap-2" onClick={onBack} style={{ backgroundColor: "#2b4cb3", border: "none" }}>
                    <i className="bi bi-arrow-left-circle"></i> Dashboard
                </button>
            </div>

            {/* ⭐ CREDIT NOTICE */}
            <div className="alert alert-danger border-0 small py-2 mb-4 text-center" style={{ backgroundColor: "transparent", color: "#e63946", border: "none" }}>
                <span className="fw-bold">You have 1 free credits to explore how this feature works. You have utilized 0 credits so far. To continue using it beyond this limit, please upgrade to the paid plan.</span>
            </div>

            {/* ⭐ SEARCH FORM */}
            <div className="row g-0 border rounded-3 mb-5 overflow-hidden">
                <div className="col-md-4 bg-light p-3 border-end d-flex align-items-center fw-bold small">
                    MCA V3 User ID
                </div>
                <div className="col-md-5 p-3 border-end">
                    <select className="form-select form-select-sm" style={{ border: "none", backgroundColor: "transparent" }}>
                        <option>Select MCA User</option>
                    </select>
                </div>
                <div className="col-md-3 p-3 bg-white d-flex align-items-center">
                    <span className="text-danger small" style={{ fontSize: "11px" }}>*HINT: Select MCA V3 User ID to fetch latest VPD SRN</span>
                </div>
            </div>

            {/* ⭐ HISTORY SECTION */}
            <div className="mt-4">
                <h6 className="fw-bold text-dark mb-3 text-uppercase">VPD - History</h6>
                
                <div className="d-flex justify-content-between align-items-center mb-3">
                    <div className="d-flex align-items-center gap-2">
                        <span className="small text-muted">Show</span>
                        <select className="form-select form-select-sm" style={{ width: "70px" }}>
                            <option>10</option>
                        </select>
                        <span className="small text-muted">entries</span>
                    </div>
                    <div className="d-flex align-items-center gap-2">
                        <span className="small text-muted">Search:</span>
                        <input className="form-control form-control-sm" style={{ width: "200px" }} />
                    </div>
                </div>

                <div className="table-responsive">
                    <table className="table table-bordered align-middle text-center small">
                        <thead className="bg-secondary text-white">
                            <tr>
                                <th>Sr. No.</th>
                                <th>Company/LLP name (CIN/LLPIN)</th>
                                <th>MCA User ID</th>
                                <th>Generated On</th>
                                <th>Generated By</th>
                                <th>SRN</th>
                                <th>Download (Receipt)</th>
                                <th>Download (Documents)</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td colSpan={8} className="text-center py-4 text-muted small">
                                    No data available in table
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <div className="d-flex justify-content-between align-items-center mt-3">
                    <div className="small text-muted">Showing 0 to 0 of 0 entries</div>
                    <div className="btn-group btn-group-sm">
                        <button className="btn btn-outline-secondary px-3 border-0">Previous</button>
                        <button className="btn btn-outline-secondary px-3 border-0">Next</button>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default ViewPublicDocumentView;
